### ISSUE TITLE
[question] can't use shortcut appid in cli game launch

### ISSUE THREAD

**Issue by Yato202010** [WilliamVenner/steamlocate-rs#16]
i have a test game that when i create a desktop shortcut use 
```steam steam://rungameid/14819369052371156992```
which indicate that the appid is ```14819369052371156992``` but using Shortcut struct i get ```4206273994``` but this one will not let me run the game. did i misunderstood how steam handle non steam game appid ?

**Comment by CosmicHorrorDev** [comment]
You're looking for the steam id. You can get it by calling `.steam_id()` provided by the `shortcuts_extras` feature
