### ISSUE TITLE
Future incompatibility warning because of steamy-vdf's dependency on nom 1.2.4

### ISSUE THREAD

**Issue by mtkennerly** [WilliamVenner/steamlocate-rs#19]
I [opened a ticket](https://github.com/meh/steamy/issues/4) for steamy-vdf, but since it doesn't seem to be maintained, I thought it was worth raising here as well for awareness.

Using Rust 1.68.0, this warning is displayed while building:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
```

**Comment by CosmicHorrorDev** [comment]
Thanks for the notice!

Something that would be extremely helpful would be more testing with #9. Just seeing if there are any parsing/deserialization issues on any manifests is the big one

**Comment by CosmicHorrorDev** [comment]
`2.0.0-alpha.0` was just published and includes the changes to fully drops `steamy-vdf` including its dependency on `nom` v1.2.4

There will be significant changes before the actual v2 release for `steamlocate`, but this should let people have access to these changes early without having to rely on git dependencies

Leaving this issue open for visibility

**Comment by mtkennerly** [comment]
I don't think there's anything to change here, but just figured I'd mention it in case anyone else runs into it. I tried integrating 2.0.0-alpha.0, and Windows Defender complained about there being a trojan. However, I wasn't able to reproduce it after rebuilding, and Virus Total didn't find any issues, so ¯\\\_(ツ)\_/¯ Otherwise, it's working fine.

> <img width="770" alt="ludusavi-steamlocate-2 0 0-alpha 0-quarantine" src="https://user-images.githubusercontent.com/4934192/228758896-65ffcaee-91cc-49ed-ba86-76ad020700d6.png">

**Comment by CosmicHorrorDev** [comment]
Rust is pretty good at getting false positives from anti-viruses because one of its initial popular uses was in malware. Mostly because static-linking makes portable executables and cross compiling a lot easier (Go is also popular here for the same reason)

**Comment by CosmicHorrorDev** [comment]
`steamy-vdf` is now fully dropped from our dep tree with the 2.0 release
