### ISSUE TITLE
Consider adding me as a crate owner

### ISSUE THREAD

**Issue by CosmicHorrorDev** [WilliamVenner/steamlocate-rs#22]
Hi @WilliamVenner!

It seems like you've been pretty busy lately. I've got quite a bit of free time on my hands lately, so I'd like to get v2 for this crate prepared with at least one alpha and beta along the way. If you wouldn't mind adding me as a crate owner I could handle working out all that and then ping you for the final review before publishing v2

**Comment by WilliamVenner** [comment]
Invite sent :)

**Comment by CosmicHorrorDev** [comment]
Accepted. Thanks!
