### ISSUE TITLE
`libraryfolders.vdf` layout changed

### ISSUE THREAD

**Issue by LovecraftianHorror** [WilliamVenner/steamlocate-rs#3]
It looks like some Steam update changed the layout used in `libraryfolders.vdf`. Here is an anonymized version from my windows install:

```vdf
"libraryfolders"
{
	"contentstatsid"		"-9876543210987654321"
	"0"
	{
		"path"		"C:\\Program Files (x86)\\Steam"
		"label"		""
		"contentid"		"-9876543210987654321"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"98765432109"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"111"		"12345678901"
			"210987"		"9998887776"
		}
	}
	"1"
	{
		"path"		"D:\\SteamLibrary"
		"label"		""
		"contentid"		"7654321098765432109"
		"totalsize"		"123456789012"
		"update_clean_bytes_tally"		"11223344556"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"10"		"101112131"
		}
	}
}
```

This matches the same layout present on my linux install

Notably there is a parse error before any information can be extracted because [`steamy-vdf` has an issue parsing empty strings](https://github.com/meh/steamy/issues/1) and the new layout contains the pair `"label"        ""`. Changing the labels' values manually to contain some text gets past the parse error and instead fails on the different layout

**Comment by LovecraftianHorror** [comment]
If you're open to it I can swap out the parser for the vdf parsing library I made, since `steamy-vdf` doesn't seem to be maintained.

It would be a breaking change since types from `steamy-vdf` are exposed directly, but it could be a good opportunity to clean up the public API a bit

**Comment by WilliamVenner** [comment]
Honestly go right ahead. I welcome any of your contributions :D
